\rm -f depend.list;
\rm -rf genesis.log;
\rm -rf genesis_work;
\rm -rf genesis_raw;
\rm -rf genesis_verif;
\rm -rf genesis_synth;
\rm -f mipsCore.xml small_mipsCore.xml tiny_mipsCore.xml;
\rm -f genesis_vlog.vf;
\rm -f genesis_vlog.synth.vf;
\rm -f genesis_vlog.verif.vf;
\rm -f genesis_clean.cmd;
