//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/v/s/r/vsriva10/EEE591/HW2/starter-02/primitives/dff.vp
//  Source template: dff
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter Width 	= Data structure of type ARRAY
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

/*******************************************************************************
 * PARAMETERIZATION
 * ****************************************************************************/

// Width (_GENESIS2_INHERITANCE_PRIORITY_) = 
//	[ 5 ]
//
// Dim (_GENESIS2_DECLARATION_PRIORITY_) = 1
//
// PipelineDepth (_GENESIS2_DECLARATION_PRIORITY_) = 1
//
// Retime (_GENESIS2_DECLARATION_PRIORITY_) = 0
//
// Flatten (_GENESIS2_DECLARATION_PRIORITY_) = 1
//
// ResetToZero (_GENESIS2_DECLARATION_PRIORITY_) = 1
//
// ResetToOne (_GENESIS2_DECLARATION_PRIORITY_) = 0
//
// Enable (_GENESIS2_DECLARATION_PRIORITY_) = 0
//
// Valid (_GENESIS2_DECLARATION_PRIORITY_) = 0
//
// FlopValid (_GENESIS2_DECLARATION_PRIORITY_) = 0
//




module dff_unq3 (
       	        input logic  [4:0] din, 
                input logic  clk, 
	        input logic  rst,


	    

                output logic [4:0] q
              );

  /* synopsys dc_tcl_script_begin
   set_dont_retime [current_design] true
   set_optimize_registers false -design [current_design]
  */  

   
   

               wire		            en;
               assign en = 1'b1 ;


               logic [4:0] rst_val;       
                assign rst_val = 5'b0  ;
 
	              //assign rst_val = '0 ;

             logic data_en ;
             assign data_en = en ;
   
          logic [4:0] q_val;
          logic [4:0] d; 

          assign    d = din ; // Delay data in to prevent inf. loops
          assign    q = q_val ; 
   
          always @ (posedge clk or negedge rst ) begin  //Latches on RST or CLK
             q_val <= (!rst) ? rst_val : ( data_en ? d : q ) ;   
          end


   
endmodule

