//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/v/s/r/vsriva10/EEE591/HW2/starter-02/primitives/hazardUnit.vp
//  Source template: hazardUnit
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

//hazardUnit.vp

module hazardUnit_unq1(
	input memRead_f1,
	input logic [5:0] opcode,
	input logic [5:0] opcode_f1,
	input logic [4:0] rfReadAddr_p0,
	input logic [4:0] rfReadAddr_p1,
	input logic [4:0] rfwrite_addr_f1,
	output logic PCWrite,
	output logic IFIDWrite
);

parameter BEQ = 6'b000100, BGTZ = 6'b000111, BNE = 6'b000101, BGEZ = 6'b000001, LW = 6'b100011;

always_comb begin
	if((opcode == BGTZ || opcode == BNE || opcode == BEQ || opcode == BGEZ) && (opcode_f1 == LW) && (memRead_f1 == 1'b1) && ((rfwrite_addr_f1 == rfReadAddr_p0) || (rfwrite_addr_f1 == rfReadAddr_p1))) begin
		PCWrite   = 1'b0;
		IFIDWrite = 1'b0;
	end
	else begin
		PCWrite   = 1'b1;
		IFIDWrite = 1'b1;
	end 
end


endmodule // hazardUnit_unq1
