//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/v/s/r/vsriva10/EEE591/HW2/starter-02/primitives/MIPSICache.vp
//  Source template: MIPSICache
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter wordLength 	= 32
// Parameter iCacheOccupancy 	= 5000000
// Parameter issueWidth 	= 1
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

//MIPSICache
// wordLength (_GENESIS2_INHERITANCE_PRIORITY_) = 32
//
// issueWidth (_GENESIS2_INHERITANCE_PRIORITY_) = 1
//
// iCacheOccupancy (_GENESIS2_INHERITANCE_PRIORITY_) = 0x4c4b40
//

module MIPSICache_unq1(
//	input logic [31:0] iCacheWriteData,
//    	input logic [31:0] iCacheWriteAddr,
//	input logic wrEn,
	output logic [31:0] iCacheReadData,
    	input logic [31:0] iCacheReadAddr
);

	logic [31:0] mem [5000000];
	
	assign iCacheReadData = mem[iCacheReadAddr];

endmodule: MIPSICache_unq1

