//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/v/s/r/vsriva10/EEE591/HW2/starter-02/primitives/MIPSDCache.vp
//  Source template: MIPSDCache
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter wordLength 	= 32
// Parameter dCacheOccupancy 	= 4096
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

//MIPSDCache
// wordLength (_GENESIS2_INHERITANCE_PRIORITY_) = 32
//
// dCacheOccupancy (_GENESIS2_INHERITANCE_PRIORITY_) = 0x1000
//

module MIPSDCache_unq1(
	input logic [31:0] dCacheWriteData,
    	input bit [31:0] dCacheAddr,
	input logic dCacheWriteEn,
	input logic dCacheReadEn,
	output logic [31:0] dCacheReadData,
	input logic clk
);
	logic [31:0] mem [bit[31:0]];

	always_comb begin
		dCacheReadData =  dCacheReadEn ? mem[dCacheAddr] : 32'b0;  
	end 
	
	always @(posedge clk)
	begin
		if(dCacheWriteEn) begin
			mem[dCacheAddr]<=dCacheWriteData;
		end

	end

endmodule: MIPSDCache_unq1

